### ISSUE TITLE
`cactus-pangenome` with fragmented draft assemblies drops contigs

### ISSUE THREAD

**Issue by MarionPerrier** [ComparativeGenomicsToolkit/cactus#1212]
Dear developers,

I am trying to create a draft pangenome of the 6 yeasts used for the example (S288C, Y12, YPS128, UWOPS034614, SK1 and DBVPG6044) + a very fragmented assembly (BY4741). 
My end goal is to create a reference pantranscriptome by indexing my pangenome with the GFF of each isolates by using `vg autoindex` (followed by `vg mpmap` and `rpvg` further down the line.)
However, it seems like `cactus-pangenome` is dropping entire contigs from the fragmented assembly, and I can't identify why these contigs are getting dropped. They do not appears in `yeast.paf.filter.log` nor `minigraph.split.log` making it difficult for me to understand what's going on. These contigs contains gene annotation, and therefore I would like them to be retained by `cactus-pangenome`.

I tried to play with the parameter `--permissiveContigFilter`, but the output result doesn't change and I still have these entire contigs dropped.

Here is the command I use for the creation of the pangenome: 

```
singularity run --cleanenv docker://quay.io/comparative-genomics-toolkit/cactus:v2.6.9 cactus-pangenome ./js input.txt --outDir yeastPg --outName yeastPg --reference S288C --vcf --giraffe --gfa --gbz --odgi --draw --viz --permissiveContigFilter 0.1 --configFile cactus_progressive_config.xml
```

The program run smoothly without throwing any error. Here is the output log: [log.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/13208926/log.txt)

However, there is no more trace of some contigs (such as "scaffold_151"): 

```
(base) marion@marion-PC:~/Documents/pangenome_assembly/test_yeast/yeastPg$ grep 'scaffold_151' yeastPg.paf.filter.log 
(base) marion@marion-PC:~/Documents/pangenome_assembly/test_yeast/yeastPg$ grep 'scaffold_151' chrom-subproblems/minigraph.split.log 
(base) marion@marion-PC:~/Documents/pangenome_assembly/test_yeast/yeastPg$
```

I attached the following files:

- [input.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/13208601/input.txt)
- [yeastPg.paf.filter.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/13208944/yeastPg.paf.filter.log)
- [minigraph.split.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/13208940/minigraph.split.log)
- [cactus_progressive_config.xml.gz](https://github.com/ComparativeGenomicsToolkit/cactus/files/13208816/cactus_progressive_config.xml.gz)  (I just changed the parameter `minigraphConstructOptions` in `graphmap` for `d=500` since this is the size of my tiniest contig.)
- The assembly of BY4741: [BY4741_prefix.fa.gz](https://github.com/ComparativeGenomicsToolkit/cactus/files/13208820/BY4741_prefix.fa.gz) 

How should I proceed to keep these contigs within my pangenome? Is it possible?

I wish you a good day,
Regards,
Marion

**Comment by glennhickey** [comment]
Thanks for sharing the data.  I will take a look.  But I think the issue is that there's a MAPQ filter happening that, in cases where it nukes the whole contig, isn't coming up in either of the logs you looked.  If that's it, you can lower or disable the filter here

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/cactus_progressive_config.xml#L331

(find that file where you installed Cactus, copy it and make the change, and pass in the copy with `--configFile`).  I

**Comment by glennhickey** [comment]
Yeah, it seems to be the MAPQ.  If we look at `scaffold_151` in the PAF

```
zcat yeastPg.paf.unfiltered.gz | grep scaffold_151
id=BY4741|scaffold_151	8094	27	8080	-	id=_MINIGRAPH_|s168	15576	3649	11702	8049	8053	1	tp:A:P	rc:Z:chrIV	gm:i:8049	gl:i:8053	gi:f:1	cg:Z:168=1X351=1X3577=1X1623=1X2330=
```
We see it has `MAPQ 1` (12th PAF column).  This gets filtered out during chromosome assignment (`cactus-graphmap-split` phase) but *before* `minigraph.split.log` gets made. 

I actually just noticed the other day that [a similar thing was happening to some reference contigs](https://github.com/ComparativeGenomicsToolkit/cactus/pull/1210) which is fixed in the latest release. 

But here, I think the tool is behaving as intended : `MAPQ=1` mappings are excluded from your graph which unfortunately drops your whole contig here.  I agree that there is a very annoying deficiency in the logging that I'll try to fix soon, though.

Reducing the MAPQ filter ought to get this contig into your graph but be warned that its alignment is apparently rather ambiguous.

**Comment by MarionPerrier** [comment]
Thank you for your answer!

Indeed, setting `minMAPQ="1"` retain some contigs, while some are still getting dropped. I guess this could be due to other parameters of graphmap.
I am going to tune a bit more the config file to try to get the best alignment while minimizing the contig loss.

Thank you!
